# helmfile for demo
# we can add repos in helmfile
# repositories:
# - name : <repository-name>
#   url: <url>

templates:
  org: &org
    namespace: default
    chart: ./organization-chart
    values: 
     - ./test-values.yaml

releases:
- name: mysql
  namespace: default
  chart: ./mysql-chart
- name: organization-service
  <<: *org

# - name: organization-service
#   namespace: default
#   chart: ./organization-chart
#   values:
#   - ./test-values.yaml
#   installed: true
