server: 
    port: 8081
    
spring:
    datasource:
#        url: jdbc:mysql://${DB_HOST}/${DB_NAME}
        url: jdbc:mysql://localhost:3306/organizationdb
        driver-class-name: com.mysql.cj.jdbc.Driver
        username: root
        password: 1234
#        username: ${DB_USERNAME}
#        password: ${DB_PASSWORD}
    jpa: 
        database-platform: org.hibernate.dialect.MySQL5Dialect
        hibernate: 
            ddl-auto: update
            
organizationService.url: http://localhost:8080/api/v1

#server.port=9002
#spring.datasource.url=jdbc:mysql://localhost:3306/hibernate
#spring.datasource.username=root
#spring.datasource.password=1234
#spring.application.name=employee-service
#eureka.instance.hostname=localhost
