apiVersion: v1
kind: Secret
metadata:
   name: {{ .Release.Name}}-secret
type: Opaque
data:
    mysql-username: {{ .Values.mysql.username }}
    mysql-password: {{ .Values.mysql.password }}
   #  mysql-username: cm9vdA==
   #  mysql-password: MTIzNA==
   